### ISSUE TITLE
jReads does not exist

### ISSUE THREAD

**Issue by npx** [kevincobain2000/jProcessing#1]
Hey there,

I compiled and installed all dependencies and now wanna run some of the examples presented [here](https://jprocessing.readthedocs.org/en/latest/#kanji-katakana-hiragana-to-tokenized-romaji-jconvert-py).

    >>> from jNlp.jConvert import *
    Traceback (most recent call last):
      File "<input>", line 1, in <module>
      File "/Users/xxx/VirtualEnvs/venv-python2.7-django/lib/python2.7/site-packages/jProcessing-0.1-py2.7.egg/j
    Nlp/jConvert.py", line 4, in <module>
        from jNlp.jTokenize import jTokenize, jReads
    ImportError: cannot import name jReads

I tried replacing the jReads with the jTokenize method but I didn't expect that to work :)

I found and old implementation that I took and changed to using `cabocha()`.

    def jReads(target_sent):
        sentence = etree.fromstring(cabocha(target_sent).encode('utf-8'))
        jReadsToks = []
        for chunk in sentence:
            for tok in chunk.findall('tok'):
                if tok.get("read"): jReadsToks.append(tok.get("read"))
        return jReadsToks

However, I don't seem to be getting a valid XML:

    気象庁が２１日午前４時４８分、発表した天気概況によると、
    tokenizedRomaji(input_sentence)

    iconv_open is not supported
                               Traceback (most recent call last):
      File "<input>", line 1, in <module>
    Nlp/jConvert.py", line 42, in tokenizedRomaji2.7-django/lib/python2.7/site-packages/jProcessing-0.1-py2.7.egg/j
        for kataChunk in jReads(jSent):
      File "/Users/xxx/VirtualEnvs/venv-python2.7-django/lib/python2.7/site-packages/jProcessing-0.1-py2.7.egg/j
    Nlp/jTokenize.py", line 29, in jReads
        sentence = etree.fromstring(cabocha(target_sent).encode('utf-8'))
      File "<string>", line 124, in XML
    ParseError: not well-formed (invalid token): line 1, column 4

I compiled and installed `iconv` but is this related to the problem?

Also, I verified my installation of `mecab` and `cabocha` and both seem to work fine.

But jReads really does not exist xP

**Comment by anyong** [comment]
Did you ever get the 'read' label issue fixed?

**Comment by kevincobain2000** [comment]
@anyong https://github.com/kevincobain2000/jProcessing/commit/d59425fb8b63365340458ec683037f4d98e7e255 fixes it. Just didn't close the issue.
